version: '3.8'

services:
  # Override settings for local development
  eyexpensemanager-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EYExpenseDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    volumes:
      - ./EYExpenseManager/EYExpenseManager.API/Storage:/app/Storage
    ports:
      - "5000:80"

  eyexpensemanager-ui:
    build:
      context: ./ey-expense-manager-ui
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=development
    volumes:
      - ./ey-expense-manager-ui/src:/app/src
    environment:
      - NODE_ENV=development
    ports:
      - "4200:80"

  # Development-specific services
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

volumes:
  seq_data:
