global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
    metrics_path: '/prometheus'

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']

  - job_name: 'dotnet-app'
    static_configs:
      - targets: ['host.docker.internal:5000']
    scrape_interval: 10s

  - job_name: 'angular-app'
    static_configs:
      - targets: ['host.docker.internal:4200']
    scrape_interval: 10s

  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sqlserver:1433']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
